def repoWorkspace

pipeline {
  agent any
  tools {
    maven "maven-jenkins"
  }
  stages {
    stage('Checkout') {
      steps {
        script {
          repoWorkspace = "${WORKSPACE}/${params.REPO_NAME}"
          dir(repoWorkspace) {
            git branch: "${params.REPO_BRANCH}", credentialsId: 'local-jenkins', url: "https://github.com/${REPO_USERNAME}/${params.REPO_NAME}.git"
          }
        }
      }
    }
    stage('Build') {
      steps {
        dir("${repoWorkspace}") {
          configFileProvider([configFile(fileId: 'mvn-settings-artifactory', variable: 'MAVEN_SETTINGS_XML')]) {
            sh 'mvn clean package'
          }
        }
      }
    }
    stage('Test') {
      steps {
        dir("${repoWorkspace}") {
          sh 'mvn test'
        }
      }
    }
    stage("Scan & Quality Gate") {
      steps {
        dir("${repoWorkspace}") {
          withSonarQubeEnv(installationName: "SonarQubeServer") {
            sh "mvn sonar:sonar"
          }
          timeout(time: 2, unit: "MINUTES") {
            waitForQualityGate abortPipeline: true
          }
        }
      }
    }
    stage('Docker Build & Push') {
      steps {
        dir("${repoWorkspace}") {
          script {
            sh "git rev-parse --short HEAD > .git/commit-id"
            gitcommit = readFile(".git/commit-id").trim()

            git branch: "main", credentialsId: 'local-jenkins', url: "https://github.com/${REPO_USERNAME}/ccpl-devops.git"

            def app = docker.build("${DOCKER_HUB_USERNAME}/${params.REPO_NAME}", "./projects/tdsmicroservices")
            docker.withRegistry("https://registry.hub.docker.com", "DockerHubCredentials") {
              app.push("${gitcommit}")
              app.push("latest")
            }

            sh "docker rmi registry.hub.docker.com/${DOCKER_HUB_USERNAME}/${params.REPO_NAME}:${gitcommit}"
            sh "docker rmi registry.hub.docker.com/${DOCKER_HUB_USERNAME}/${params.REPO_NAME}:latest"

          }
        }

      }
    }
  }
  post {
    success {
      slackSend message: "Build successfully - ${env.REPO_NAME} # ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
    }
    failure {
      slackSend message: "Build failed - ${env.REPO_NAME} # ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
    }
  }
}