name: Publish Artifact

on:
  workflow_call:
    secrets:
      USERNAME:
        required: true
      USERNAME_ACCESS_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
    inputs:
      IS_SNAPSHOT:
        required: true
        type: boolean

permissions:
  contents: write
  actions: read
  packages: write

jobs:
  build:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: "warning",
                text: "Publish Artifact Pipeline has been started for the component ${{ github.event.repository.name }}. Author: ${{ github.actor }}."
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Set Up Maven Settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [
              {
                "id": "github",
                "username": "${{ secrets.USERNAME }}",
                "password": "${{ secrets.USERNAME_ACCESS_TOKEN }}"
              }
            ]
          repositories: |
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/CCPL-Solutions/gdmt-lib-commons"
              }
            ]

      - name: Validate Version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version: $version"
          if [[ "${{ inputs.IS_SNAPSHOT }}" == "true" && "$version" != *-SNAPSHOT ]]; then
            echo "Expected a SNAPSHOT version but found: $version"
            exit 1
          fi
          if [[ "${{ inputs.IS_SNAPSHOT }}" == "false" && "$version" == *-SNAPSHOT ]]; then
            echo "Expected a RELEASE version but found SNAPSHOT: $version"
            exit 1
          fi

      - name: Build and Publish
        run: |
          if [ "${{ inputs.IS_SNAPSHOT }}" = "true" ]; then
            echo "Publishing SNAPSHOT version..."
            mvn clean deploy -DskipTests=true
          else
            echo "Publishing RELEASE version..."
            mvn clean deploy -DskipTests=true
          fi

      - name: Create Release Branch
        if: ${{ inputs.IS_SNAPSHOT == true }}
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          branch=release/$version
          branch=${branch//-SNAPSHOT/}
          echo "Creating branch $branch ..."
          git config user.name "admghub-ccplsolutions"
          git config user.email "admgithub.ccplsolutions@outlook.com"
          git fetch origin
          if git ls-remote --exit-code --heads origin "$branch"; then
            echo "Branch $branch already exists. Deleting it..."
            git push origin --delete "$branch"
          fi
          git checkout origin/develop
          git checkout -b "$branch"
          git push https://x-access-token:${{ secrets.USERNAME_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,repo,message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  manual-approval:
    name: Approve Release
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: release-approval
      url: https://github.com/${{ github.repository }}/branches
    steps:
      - name: Waiting for manual approval
        run: echo "Waiting for approval to finalize the release..."

  finalize-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout Release Branch
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          branch=release/$version
          branch=${branch//-SNAPSHOT/}
          echo "Current branch"
          git branch --show-current
          echo "Checking out branch $branch ..."
          git fetch origin
          git checkout "$branch"

      - name: Get version from pom.xml
        id: get_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Remove -SNAPSHOT from pom.xml
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          release_version="${version/-SNAPSHOT/}"
          echo "Setting release version to $release_version"
          mvn versions:set -DnewVersion=$release_version
          mvn versions:commit

      - name: Commit and Push Version Update
        run: |
          git config user.name "admghub-ccplsolutions"
          git config user.email "admgithub.ccplsolutions@outlook.com"
          git commit -am "chore: finalize release version"
          git push https://x-access-token:${{ secrets.USERNAME_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          echo "Current branch 2"
          git branch --show-current



      - name: Set Up Maven Settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [
              {
                "id": "github",
                "username": "${{ secrets.USERNAME }}",
                "password": "${{ secrets.USERNAME_ACCESS_TOKEN }}"
              }
            ]
          repositories: |
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/CCPL-Solutions/gdmt-lib-commons"
              }
            ]

      - name: Build and Publish
        run: |
          echo "Publishing RELEASE version..."
          mvn clean deploy -DskipTests=true

      - name: Merge Release into Master
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          release_branch=release/${version/-SNAPSHOT/}
          echo "Current branch3"
          git branch --show-current
          echo "Merging $release_branch into master..."
          git fetch origin
          git checkout master
          git pull
          echo "Current branch4"
          git branch --show-current
          git merge --no-ff origin/$release_branch -m "chore: merge $release_branch into master" --allow-unrelated-histories
          git push https://x-access-token:${{ secrets.USERNAME_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Merge Release into Develop
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          release_branch=release/${version/-SNAPSHOT/}
          echo "Merging $release_branch into develop..."
          git fetch origin
          git checkout develop
          git merge --no-ff origin/$release_branch -m "chore: merge $release_branch into develop" --allow-unrelated-histories
          git push https://x-access-token:${{ secrets.USERNAME_ACCESS_TOKEN }}@github.com/${{ github.repository }}

