name: Push Event Workflow

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  build:
    name: Buid
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: "warning",
                text: "Push event has been triggered for the component *${{ github.event.repository.name }}*. Author: *${{ github.actor }}*"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Copy custom settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven-settings/settings.xml ~/.m2/settings.xml

      - name: Print settings.xml
        run: cat ~/.m2/settings.xml

      - name: Build With Maven
        run: mvn clean install -s .github/maven-settings/settings.xml -DskipTests=false
        env:
          GITHUB_ACTOR_SETTINGS: ${{ secrets.USUARIO_EXAMPLE }}
          GITHUB_TOKEN_SETTINGS: ${{ secrets.TOKEN_EXAMPLE }}

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,repo,message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
