name: Push Event Workflow

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Buid
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: "warning",
                text: "Push event has been triggered for the component *${{ github.event.repository.name }}*. Author: *${{ github.actor }}*"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Configure Maven for GitHub Packages
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "myGithub",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
          repositories: |
            [{
              "id": "myGithub",
              "url": "https://maven.pkg.github.com/CCPL-Solutions/gdmt-lib-commons",
              "snapshots":{"enabled":true}
            }]

      - name: Build With Maven
        run: mvn clean install -DskipTests=false

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,repo,message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
