name: Push Event Workflow

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "text": "A push event has been triggered for the component `${{ github.event.repository.name }}`."
            }